# Generated by Django 6.0.6 on 2026-06-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='audit_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statement',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='raw_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(default='debit', max_length=10),
        ),
    ]
